version: "3.7"

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    # volumes:
    #   - .:/app
    command: yarn dev
    networks:
      - common
    environment:
      PORT: 3000
      MONGO_URL: "mongodb://mongo/example"
      NODE_ENV: "development"
  mongo:
    restart: always
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    # volumes:
    #   - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass      
    networks:
      - common

  mongo-ui:
    restart: always
    image: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    ports:
      - 8081:8081
    networks:
      - common

networks:
  common:
